LibertyDSNP/example-client

src/components/Login.tsx
src/components/test/Login.test.tsx
src/components/test/LoginSetupInstructions.test.tsx
src/redux/slices/userSlice.ts
src/services/sdk.ts

Purpose
Once the user has logged in with Metamask or Torus, we only have a wallet address. We need to have a DSNP id to interact with any of the content.
Solution
This PR adds the SDK call to retrieve DSNP registrations by wallet address. It then simply picks the first one available. It uses it then gets the user's id from its dsnpURI.
Change summary
* Replace fake `sdk.getSocialIdentity` method with one that calls `getRegistrationsByWalletAddress`
* Rearrange login code so provider is set before `getSocialIdentity` is called.
* Mock the getSocialIdentity call in tests.
1. Ensure you metamask account address is one of the ones in the generator script (this is necessary to have a balance anyway).
2. Sst up the …

Retrieve DSNP Id

---

src/components/ConnectionsListProfiles.tsx
src/components/Profile.tsx
src/components/test/ConnectionsListProfiles.test.tsx
src/components/test/ProfileBlock.test.tsx
src/redux/slices/profileSlice.ts
src/services/sdk.ts
src/test/testGraphs.ts
src/utilities/types.d.ts

Purpose
When we edit a profile, we want to actually send the change out to the DSNP network so others know about it and the change is persisted.
Solution
This PR wires the edit profile functionality to a new SDK method that creates and publishes a new profile.
Change summary
* Create `sdk.saveProfile` method (with some sdk refactoring to reduce redundancy).
* Wire the Profile edit functionality to call the save profile.
* Track blockNumber, blockIndex and batchIndex, so we can correctly order profile changes.
* Add comparison logic in the profile slice of the redux store to ensure we always show the latest profile.
* Address some feedback that came in late from #58.
1. Set up the app with the usual steps.
2. …

save profiles

---

src/App.test.tsx
src/App.tsx
src/services/sdk.ts

Ensure that feed does not display unwanted duplicate post.
After creating a post, feed shows duplicates.
This happens when attempting to create a post
after re-login into account.
The cause of this behavior was a result of
not unsubscribing to events when app page
gets unmounted.

fix(feed): remove duplicate post

---

src/services/sdk.test.ts
src/services/sdk.ts

Logging out was broken because on subscribing to batch publications we should have been `await`ing the result. So when we went to unsub it would throw because the result was a Promise and not a function.
[Fixes #179292977](https://www.pivotaltracker.com/story/show/179292977)
Solution
SUPER short fix, annoyingly tedious to construct regression test that shows the red/green behavior.
1.  Tests should all pass
1.  If you remove the "await" from the call to `core.contracts.subscription.subscribeToBatchPublications`, the test should fail.
1.  You should be able to logout without exception now.

fix problem with subscriptions + test

---

src/App.scss
src/components/BlankPost.tsx
src/components/BlankReply.tsx
src/components/Feed.tsx
src/components/NewPost.tsx
src/components/Post.tsx
src/components/PostList.tsx
src/components/Profile.tsx
src/components/Reply.tsx
src/components/ReplyBlock.tsx
src/components/ReplyInput.tsx
src/components/scss/BlankPost.scss
src/components/scss/BlankReply.scss
src/components/test/Feed.test.tsx
src/redux/slices/feedSlice.ts
src/services/Storage.ts
src/services/sdk.ts
src/theme/_mixins.scss

Purpose
Feature
[https://www.pivotaltracker.com/story/show/179073406](url)
Solution
As a user, I want to see that my post or reply is loading after I post it.  create gray loading placeholder post/reply.
Change summary
* keep track of new post loading, new reply loading, and reply parent in the redux store
* create Blank Post and Blank Reply
* display the two above components based on the above redux state
1. create a post
2. create a reply
3. have multiple posts and multiple replies
*** Does this work if multiple people are posting are once?
https://user-images.githubusercontent.com/43625033/129978702-da5db0b6-becf-41b6-9e8c-069021f319ac.mov

add spinner to posts and replies while loading

---

src/components/PostList.tsx
src/components/ReplyBlock.tsx
src/components/test/Feed.test.tsx
src/components/test/PostList.test.tsx
src/components/test/ReplyBlock.test.tsx
src/redux/slices/feedSlice.ts

Purpose
[Pivotal Tracker Story #179276259](https://www.pivotaltracker.com/story/show/179276259)
Our posts were not being rendered in the correct order. This is because our call to retrieve activity pub content and send it to redux is async. This means content of posts is not always stored in redux in the same order that it is stored on chain. 
Solution
Before rendering posts we need to sort them by block number to ensure that they are in the correct order. 
Change summary
* Add a function to `PostList.tsx` to ensure that posts are ordered.
* rename `feed` to `feedItems` so that we are not referring to `state.feed.feed` but rather state.feed.feedItems
* Add tests

fix inconsistent ordering of posts

---

src/redux/slices/feedSlice.ts

Purpose
A bug was introduced into the feed reducer that prevented all existing feed items from entering redux state and displaying in the feed. This PR attempts to keep the spirit of the erroneous code with limiting the posts.
Solution
A condition was added in the feed reducer that prevented the item from being added to the store if it did not match other state set by the NewPost component. This would reject all posts from other people in order to avoid the wrong posts changing the loading state. This PR limits this condition only to the loading state and allows all posts into state.
Change summary
* Remove `(state.isPostLoading.currentUserId === newFeedItem.fromId)` clause.
* Replace with `newPostLoadingState` and `newReplyLoadingState` …

fix feed loading

---

src/components/Post.tsx
src/components/PostHashDropdown.tsx
src/components/Reply.tsx
src/components/test/Feed.test.tsx
src/test/testFeeds.ts

Purpose
copy announcement URI instead of just the hash
Solution
create announcement URI based off of the spec: [https://spec.dsnp.org/Identifiers#dsnp-announcement-uri](url)
Change summary
* bring in fromId to PostHashDropdown
* create proper announcementURI
1. Check that value copied is correct

Feature/annoucement id copy button/179257443

---

src/services/Storage.ts
src/services/sdk.ts
src/utilities/buildBaseUploadHostUrl.test.ts
src/utilities/buildBaseUploadHostUrl.ts

Purpose
We needed a small function to differentiate when we need a fully qualified url or just the information for the 
`REACT_APP_UPLOAD_HOST`. 
This is because we are serving the react app statically from the static server in our Dockerfile, and so the `REACT_APP_UPLOAD_HOST` is the same as the base url for the static sever. In certain places in the code we use `fetch` to resolve a url - which is able to resolve an empty `REACT_APP_UPLOAD_HOST` to the base url of the server. However in other places we are just building a URL and so need to find the fully qualified URL. 
Solution
Write a small utility function that will return a qualified url when needed. 
Change summary
* Add a small utility function that will return a qualified Url when …

add utility to build react upload host url

---

src/services/dsnp.ts

Purpose
Announcements must be properly signed in order to be accepted by compliant DSNP clients. This PR adds that functionality to the example client. Note that this now requires two confirmations from the wallet for every DSNP change made: one for the announcement and another to sign the batch it goes into.
Solution
Add signing to all create and sign content methods.
1. Start the app and sign in.
2. Create a post.
3. Note that the app requires you to sign the message with the wallet before asking you to sign the transaction.
4. Reply to a post.
5. Note that the app requires you to sign the message with the wallet before asking you to sign the transaction.
6. Change your name in the profile.
7. Note that the app requires …

sign all announcements

---

.eslintrc.json
package-lock.json
package.json
scripts/populate.mjs
src/App.test.tsx
src/components/ConnectionsList.tsx
src/components/ConnectionsListProfiles.tsx
src/components/Feed.tsx
src/components/Login.tsx
src/components/NewPost.tsx
src/components/PostList.tsx
src/components/Profile.tsx
src/components/ProfileBlock.tsx
src/components/RegistrationModal.tsx
src/components/test/Login.test.tsx
src/components/test/LoginSetupInstructions.test.tsx
src/components/test/RegistrationModal.test.tsx
src/redux/slices/graphSlice.ts
src/redux/slices/userSlice.ts
src/services/Storage.ts
src/services/content.ts
src/services/dsnp.ts
src/services/session.ts
src/test/testGraphs.ts
src/test/testProfiles.ts
src/utilities/buildBaseUploadHostUrl.test.ts
src/utilities/buildBaseUploadHostUrl.ts
src/utilities/types.d.ts

Purpose
Significant breaking changes were made in SDK 3.0. This PR makes necessary changes to incorporate these changes.
Solution
The SDK now returning DSNPUserId as a BigInt drives most of the changes in this PR. BigInt is not serializable, so it can't be stored in Redux and it cannot be used as a map key. Our approach is to convert all id's to strings (as they were before) before storing them and occasionally converting them back when submitting content back to the SDK. 
One of the bigger changes is that we now create a completely new `Profile` type to be used within the example-client rather than union-ing SDK types and adding fields. This allows us to normalize some behavior between registry updates and profile upgrades. 
We also take advantage of some …

upgrade to sdk 3

---

src/utilities/buildBaseUploadHostUrl.test.ts
src/utilities/buildBaseUploadHostUrl.ts

Purpose
Bug - the protocol is missing from `window.location` - so we need to add it to retrieve the appropriate fully qualified url.
Solution
Add `window.protocol` to `window.location` in `buildBaseUploadHostUrl`
Change summary
* add protocol to `window.location` in `buildBaseUploadHostUrl`
* fix spec.

add protocol to base url

---

src/components/Feed.tsx
src/components/Login.tsx
src/components/PostList.tsx
src/components/test/Feed.test.tsx
src/redux/slices/userSlice.ts
src/test/testAddresses.ts
src/test/testProfiles.ts

Purpose
[https://www.pivotaltracker.com/story/show/177349009](url)
feature
Solution
As a user, I want to click on a profile, see their profile information in the profile component, and see their posts in the feed component.
- Filter feed to only the selected user's posts
- follow wireframes for styling
Change summary
* onclick of a user's profile, display their feed in addition to their profile
* update redux store to not throw a console error (leftover from main)
* write new tests for new functionality
* correct old failing tests
1. click on others profile
2. see their profile
3. see their posts
4. see their name as the active tab in feed nav
5. click back button
6. go back to discover and my profile
7. …

show other's posts in feed + tests

---

src/components/Post.tsx
src/components/PostList.tsx
src/components/PostMedia.tsx
src/services/content.ts
src/services/dsnp.ts
src/utilities/types.d.ts

Purpose
[https://www.pivotaltracker.com/story/show/179376055](url)
Currently, on QA the loading of the feed fails because we are unsafely casting to the type of ActivityContentAttachment[] when somehow one of the pieces of data on QAnet has a null.
Solution
* We should be safely casting the content to the Activity Content type by validating the content and using a type narrowing is so that we can trust our types.
Change summary
- change the way that we are storying the type of batch announcements to be the correct type instead of storing them all as broadcasts.
- update types to stop using "as ..." and instead type check using "is"
1. make sure that null data coming through QA net does not throw an error …

changes made to storing batch announcements and note attchment typing

---

src/components/Login.tsx

Purpose
feature
restart of [https://www.pivotaltracker.com/story/show/179380420](url)
Solution
Add listener for chain Changed and logout on event.
Change summary
* add `chainChanged` listener
1. login
2. change networks
3. see logout happen
- the network change listener is deprecated, so this is the one that is the closest fitting.  is there a case in which the network changes but the chain id does not? [https://docs.metamask.io/guide/ethereum-provider.html#table-of-contents](url)

on chain id change, logout

---

package-lock.json
package.json
src/components/ConnectionsListProfiles.tsx
src/components/RegistrationModal.tsx
src/components/test/RegistrationModal.test.tsx
src/services/content.ts
src/services/dsnp.ts
src/services/session.ts
tsconfig.json

Purpose
We were using an old version of the sdk
[PT #179426683](https://www.pivotaltracker.com/story/show/179426683)
Solution
Update to v3.0.3
Change summary
* Update SDK from v3.0.2 -> 3.0.3
* Use `HexString` from the SDK
* Replace sdk/dist/types with just sdk

Update SDK package to v3.0.3

---

src/services/content.ts

Purpose
The example client should not accept improperly signed announcements. This PR rectifies that.
I needed to check that EC was sending valid signatures, and adding this authorization was the easiest way. Now that it's there I don't see any reason to get rid of it.
Solution
Add check to ignore announcements if a) they're not SignedAnnocements b) their signature does not resolve to a designated authority with announce privileges on chain. 
Change summary
* Add checks described above.
1. Should work the same as it used to.
2. You can modify the code to produce a bad signature and confirm an error appears in the console and the post does not appear in the feed.

authorize announcement messages before dispatching

---

src/services/dsnp.ts

Purpose
Speed up the loading of subscriptions on non-dsnp only testnets (like Rinkeby).
Solution
SDK v3.0.3 added the ability to start at the "dsnp-start-block" instead of just starting at the chain genesis block, so use that to start subscriptions from instead of block `1`
Change summary
* Switch subscription fromBlock to "dsnp-start-block"
1. Open the inspector for MetaMask
2. Set MetaMask to Rinkeby
3. Set the EC wallet type to MetaMask
4. See that the network request from MetaMask starts with something greater than "0x1"
Old (Registry):
New (Registry):
New for Publications:

Use the new v3.0.3 "dsnp-start-block"

---

src/App.scss
src/components/EditAvatarModal.tsx
src/components/Profile.tsx
src/components/UserAvatar.tsx
src/components/scss/EditAvatarModal.scss
src/components/test/EditAvatarModal.test.tsx
src/redux/slices/userSlice.ts
src/utilities/activityContent.ts

Purpose
Feature
As a user, I should be able to edit my profile picture
[https://www.pivotaltracker.com/story/show/179324830](https://www.pivotaltracker.com/story/show/179324830)
Solution
- onClick of the edit button in the profile component you should be able to edit your profile picture with a new URL.
Change summary
* Create EditAvatarModal that gives the user a UI to upload their new profile photo and returns the ActivityContentImageLink value.
* if edited, save the new profile icon in the Profile component
* create temp icon uri state that displays that new icon until the real iconURL is completely loaded
* styling for the new UI
* test for the new UI
* if you cancel it clears inputs/states
1. click edit …

edit profile picture modal

---

src/components/scss/Post.scss
src/components/scss/Reply.scss

Purpose
Bug
[https://www.pivotaltracker.com/story/show/179596345](https://www.pivotaltracker.com/story/show/179596345)
If there is a very long string, it was overflowing.  We want to hyphenate the string instead.
Solution
Hyphenate and word break in scss. Make compatible for all browsers.
Change summary
* Add hyphens and word break in scss
* Apply this same formatting to replies
1. type in a string like "hdhdhddhhdhdhdhdhdhdhhdhdhdbdbdbeuwywguwushsvsvdbjdjdbdbdbdbdbbddbbdbdbdbdbdbdbdbbdbdbbdbdheuwuuehehehehehehjejejejdjdjdhhdhdhdhdhdhdhhhdhdhdhdhdbdbhddhhdhdhhdhdhdhdhdhdhdhdhhdhdhdhdhdhhdhdhdhdhdhhdhdhdhdhhdhdhdhdhdhhdhdhdbdbbdbdbdbdbdbdbbdbdbdbwuueueyyeyeyehehehebdbdbbdbyxjdjfjcjcjvjcivivivivivivivivivicjcjvj …

add auto hyphenation for all browsers

---

src/App.scss
src/components/CreateRegistration.tsx
src/components/EditRegistration.tsx
src/components/EditRegistrationAccordion.tsx
src/components/RegistrationPreview.tsx
src/components/SelectHandle.tsx
src/components/scss/RegistrationPreview.scss

Purpose
Feature
[https://www.pivotaltracker.com/story/show/179585383](https://www.pivotaltracker.com/story/show/179585383)
As a user, I want to see a preview of my profile when selecting handles.
Solution
- Add profile preview in the editRegistration component
- style after the above wireframes in zeplin
Change summary
* created RegistrationPreview component
* styled accordingly
* passed the user info to preview into that component
1. try logging in and selecting a handle.
2. see your profile preview
https://user-images.githubusercontent.com/43625033/134993890-b9aa9fc0-2eff-4955-b54a-ed8059747937.mov

Feature/profile preview in edit registration/179585383

---

src/components/ConnectionsList.tsx
src/components/ConnectionsListProfiles.tsx
src/components/test/ConnectionsList.test.tsx
src/components/test/ConnectionsListProfiles.test.tsx
src/components/test/EditRegistration.test.tsx

Purpose
As a user, I want to see the correct follower/following list based on my graph.
Solution
Set and filter the connectionsList in the parent component, `ConnectionsList` instead of in the child component.  We were not initially filtering out the users that did not have the correct status, therefor giving us an inaccurate count in cases such as if you are following then unfollow a user.
Change summary
* made connectionsList a function that is passed the list that we want to filter.
* calls connectionsList(followers/following).length to get followers/following count
* calls connectionsList(currentRelation) to get open connections list and sends that as a prop to `ConnectionsListProfiles`;
1. Follow a user …

Bug/follow unfollow graph state update/179326255

---

src/components/EditRegistrationAccordion.tsx
src/components/NewPostImageUpload.tsx
src/components/scss/NewPostImageUpload.scss

Purpose
As a user, I would like to be able to see a thumbnail for the video that I am attempting to include in a new post rather than the default icon, which looks like there is an error with the link.
Solution
- If there is a thumbnail in the metadata, show that thumbnail.
- else, display a video icon so it at least looks valid
Change summary
* remove console.logs that got in from former PR
* created `getThumbnail` function that checks if youtube, vimeo, or image, and returns the thumbnail URL or null;
* if thumbnail is null, display alt thumbnail image
* add scss for alt thumbnail
- works for Youtube, Vimeo, mp4, and any other accepted video formats
- if you upload a link that is valid but does not provide …

Feature/display video thumbnail/179326255

---

src/services/dsnp.ts

Purpose
bug
[https://www.pivotaltracker.com/story/show/179581421](https://www.pivotaltracker.com/story/show/179581421)
When I load https://dev-expclient.liberti.social/ in Chrome, I see media.
When I load https://dev-expclient.liberti.social/ in Firefox (93.0b4) media does not load (looks like a float clear type issue).
Solution
- update firefox
- add try catch so it doesn't blow up if it fails to ready the url
Change summary
* add try catch to read url
1. run ec in firefox and check that your browser is updated and it works

added try catch when opening a parquet file

---

.github/workflows/docker-release.yml
.github/workflows/tagComparison.js

Problem
[Finishes 179608496](https://www.pivotaltracker.com/n/projects/2436354/stories/179608496)
Currently our docker latest tag is not automatically updated when a new tag version of example client is pushed.
Solution
Changed docker workflow to update latest version when a new version of example client is pushed.
Change summary
* Updated the docker-release yaml file
* Checks if newest version is greater than the last latest version before updating

fix docker deploy to update latest version when needed

---

src/components/scss/EditRegistration.scss

Purpose
bug
Related GitHub Issues
[https://github.com/LibertyDSNP/example-client/issues/142](https://github.com/LibertyDSNP/example-client/issues/142)
Solution
adjust styling to have cancel button on the line above the title.
Change summary
* Changed css to use flexbox
* removed absolute styling
* create build to see that it was correct there and not just in dev
1. make sure it looks correct
-

cancel button showing

---

src/components/scss/CreateRegistration.scss

Purpose
bug
Related GitHub Issues
[https://github.com/LibertyDSNP/example-client/issues/139](https://github.com/LibertyDSNP/example-client/issues/139)
Solution
remove excess padding
Change summary
* remove excess padding on button
* ran a deployment of the github pages to check the build version looked good
1. see that text is centered

centered text on button

---

src/components/ConnectWallet.tsx
src/components/EditRegistration.tsx
src/components/scss/EditRegistration.scss

Purpose
Currently, clicking out of the editRegistration popover would close the modal. The purpose of this is to make it so that users have to click on the cancel button in order to close the menu and not anything else.
Related GitHub Issues
[Github Issue #141](https://github.com/LibertyDSNP/example-client/issues/141)
Solution
- Made the modal to be restricted to only closing on a cancel click
Change summary
- Removed a function that no longer was used with the new functionality
- Added an additional cancel button after a user logged in since there is no cancel button on the registration modal after logged in.
1. Switch MetaMask to an account that does NOT have any registrations.
2. Press …

edit registration modal only closes on log in
